### ISSUE TITLE
Race condition results in NPE in FileWriter.dumpFile

### ISSUE THREAD

**Issue by preston-m-price** [Azure/kafka-sink-azure-kusto#68]
We've had several tasks do down over the last few days due to an NPE in FileWriter.dumpFile at [this line](https://github.com/Azure/kafka-sink-azure-kusto/blob/6dbd611a0fbad324cc27430ed3a61fe5e447c8b4/src/main/java/com/microsoft/azure/kusto/kafka/connect/sink/FileWriter.java#L167):
```
boolean deleted = currentFile.file.delete();
```

The stack trace associated with this NPE is:
```
java.lang.NullPointerException
at com.microsoft.azure.kusto.kafka.connect.sink.FileWriter.dumpFile(FileWriter.java:202)
at com.microsoft.azure.kusto.kafka.connect.sink.FileWriter.finishFile(FileWriter.java:182)
at com.microsoft.azure.kusto.kafka.connect.sink.FileWriter.close(FileWriter.java:215)
at com.microsoft.azure.kusto.kafka.connect.sink.TopicPartitionWriter.close(TopicPartitionWriter.java:251)
at com.microsoft.azure.kusto.kafka.connect.sink.KustoSinkTask.close(KustoSinkTask.java:356)
at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:405)
at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:639)
at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1300(WorkerSinkTask.java:71)
at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsRevoked(WorkerSinkTask.java:719)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.invokePartitionsRevoked(ConsumerCoordinator.java:312)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinPrepare(ConsumerCoordinator.java:702)
at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:423)
at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:366)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:508)
at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1262)
at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1231)
at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:452)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:324)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:241)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Suppressed: java.lang.NullPointerException
at com.microsoft.azure.kusto.kafka.connect.sink.KustoSinkTask.close(KustoSinkTask.java:356)
at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:405)
at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:639)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:202)
... 7 more
```

In this case Kafka Connect was revoking the topic-partition in question, presumably to move it to another worker, when the NPE was thrown. My current theory is that this happened while a flush timer was being evaluated to flush the same file.
Thread1 (flush timer): flushByTimeImpl -> isDirty -> finishFile -> isDirty -> dumpFile
Thread2 (connect worker task): TopicPartitionWriter.close -> FileWriter.close -> FileWriter.finishFile -> isDirty -> dumpFile

Both threads could get past the isDirty check and into the dumpFile method where one thread could set `currentFile` = null before the other thread has a chance to evaluate `currentFile.file.delete()`. 

It would be trivial to change that line to:
```
boolean deleted = currentFile == null ? false : currentFile.file.delete();
```
to protect against the NPE, but there may be a better way to get isolation into that method by leveraging the `reentrantReadWriteLock` but that lock is currently being refactored in [this PR](https://github.com/Azure/kafka-sink-azure-kusto/pull/67/files).

**Comment by preston-m-price** [comment]
If we go with the above approach we'll also need to ensure that the log statement doesn't dereference the null `currentFile`.

**Comment by preston-m-price** [comment]
I think this may actually be a defect introduced on [my PR](https://github.com/Azure/kafka-sink-azure-kusto/pull/66) when I had tried to fix [this issue](https://github.com/Azure/kafka-sink-azure-kusto/issues/64). The path from `TopicPartitionWriter.close()` -> `FileWriter.close()` was introduced in my change.
